/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import konektor.koneksi;



/**
 *
 * @author LENOVO
 */
public class Grafik extends javax.swing.JPanel {
    
    private List<String> listTanggal = new ArrayList<>();
    private List<Double> listTotal = new ArrayList<>();
    

    /**
     * Creates new form Grafik
     */
    public Grafik() {
        initComponents();
        initSpinnerTanggal();
      
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initSpinnerTanggal() {
        
        // Spinner Tanggal Mulai
    SpinnerDateModel modelMulai = new SpinnerDateModel(
        new java.util.Date(),          // nilai awal
        null,                // min
        null,                // max
        Calendar.DAY_OF_MONTH
    );
    spnMulai.setModel(modelMulai);
    spnMulai.setEditor(
        new javax.swing.JSpinner.DateEditor(spnMulai, "dd-MM-yyyy")
    );

    // Spinner Tanggal Akhir
    SpinnerDateModel modelAkhir = new SpinnerDateModel(
        new java.util.Date(),
        null,
        null,
        Calendar.DAY_OF_MONTH
    );
    spnAkhir.setModel(modelAkhir);
    spnAkhir.setEditor(
        new javax.swing.JSpinner.DateEditor(spnAkhir, "dd-MM-yyyy")
    );
        
      
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnMulai = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnAkhir = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelGrafik = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                if (listTotal.size() < 2) {
                    g.drawString("Data tidak cukup untuk grafik (minimal 2 hari)", 20, 20);
                    return;
                }

                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(
                    RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON
                );

                int pad = 40;
                int w = getWidth() - 2 * pad;
                int h = getHeight() - 2 * pad;

                // Cari nilai maksimum
                double max = Collections.max(listTotal);

                double xDiv = (double) w / (listTotal.size() - 1);
                double yDiv = (double) h / max;

                // Garis grafik
                g2.setColor(new Color(0, 102, 204));
                g2.setStroke(new BasicStroke(3f));

                for (int i = 0; i < listTotal.size() - 1; i++) {
                    int x1 = pad + (int) (i * xDiv);
                    int y1 = (getHeight() - pad) - (int) (listTotal.get(i) * yDiv);

                    int x2 = pad + (int) ((i + 1) * xDiv);
                    int y2 = (getHeight() - pad) - (int) (listTotal.get(i + 1) * yDiv);

                    g2.drawLine(x1, y1, x2, y2);
                    g2.fillOval(x1 - 4, y1 - 4, 8, 8);
                }

                // Titik terakhir
                int lastX = pad + (int) ((listTotal.size() - 1) * xDiv);
                int lastY = (getHeight() - pad)
                - (int) (listTotal.get(listTotal.size() - 1) * yDiv);
                g2.fillOval(lastX - 4, lastY - 4, 8, 8);

                // Axis
                g2.setColor(Color.BLACK);
                g2.setStroke(new BasicStroke(1f));
                g2.drawLine(pad, getHeight() - pad, getWidth() - pad, getHeight() - pad); // X
                g2.drawLine(pad, pad, pad, getHeight() - pad); // Y
            }
        };

        setBackground(new java.awt.Color(0, 0, 102));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRAFIK PENJUALAN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 577;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masukkan Tanggal   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 28, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        spnMulai.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 28, 0, 0);
        jPanel1.add(spnMulai, gridBagConstraints);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("S/D");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 18, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        spnAkhir.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 6, 0, 0);
        jPanel1.add(spnAkhir, gridBagConstraints);

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 29, 0, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        panelGrafik.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(panelGrafik);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 749;
        gridBagConstraints.ipady = 211;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(33, 0, 98, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGrafik;
    private javax.swing.JSpinner spnAkhir;
    private javax.swing.JSpinner spnMulai;
    // End of variables declaration//GEN-END:variables

    
    private void LoadData() {
        listTanggal.clear();
        listTotal.clear();

        try {
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String mulai = sdf.format(spnMulai.getValue());
            String sampai = sdf.format(spnAkhir.getValue());
            
            System.out.println("Mulai: " + mulai);
            System.out.println("Sampai: " + sampai);
            
            Connection c = koneksi.Go();
            String sql = """
                SELECT tanggal, SUM(total) AS total_harian
                FROM penjualan
                WHERE tanggal >= ? AND tanggal <= ?
                GROUP BY tanggal
                ORDER BY tanggal
            """;

            PreparedStatement ps = c.prepareStatement(sql);
            ps.setString(1, mulai);
            ps.setString(2, sampai);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                listTanggal.add(rs.getString("tanggal"));
                listTotal.add(rs.getDouble("total_harian"));
            }

            System.out.println("Jumlah data: " + listTotal.size());
            System.out.println("Jumlah data: " + listTotal.size());
            System.out.println("Tanggal: " + listTanggal);
            System.out.println("Total: " + listTotal);

            panelGrafik.repaint(); // 🔥 INI KUNCINYA

        } catch (Exception e) {
            e.printStackTrace();
        }
     
    }
}
