/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.SpinnerDateModel;
import konektor.koneksi;


/**
 *
 * @author LENOVO
 */
public class Grafik extends javax.swing.JPanel {
    
    private List<String> listTanggal = new ArrayList<>();
    private List<Double> listTotal = new ArrayList<>();
    

    /**
     * Creates new form Grafik
     */
    public Grafik() {
        initComponents();
        initSpinnerTanggal();
        
         panelGrafik = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            drawGrafik(g);
        }
        };

    panelGrafik.setPreferredSize(new Dimension(700, 300));
    panelGrafik.setBackground(java.awt.Color.WHITE);

    // GANTI panelGrafik lama di layout
    this.removeAll();
    initComponents();
    this.revalidate();
    this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnMulai = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnAkhir = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        panelGrafik = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRAFIK PENJUALAN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Masukkan Tanggal   ");

        spnMulai.setModel(new javax.swing.SpinnerDateModel());

        jLabel2.setText("S/D");

        spnAkhir.setModel(new javax.swing.SpinnerDateModel());

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGrafikLayout = new javax.swing.GroupLayout(panelGrafik);
        panelGrafik.setLayout(panelGrafikLayout);
        panelGrafikLayout.setHorizontalGroup(
            panelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );
        panelGrafikLayout.setVerticalGroup(
            panelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(spnMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(panelGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spnAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(46, 46, 46)
                .addComponent(panelGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelGrafik;
    private javax.swing.JSpinner spnAkhir;
    private javax.swing.JSpinner spnMulai;
    // End of variables declaration//GEN-END:variables

    
    class GrafikPanel extends JPanel {
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        drawGrafik(g);
    }
}

    
    private void initSpinnerTanggal() {
        SpinnerDateModel mulai = new SpinnerDateModel(
                new java.util.Date(), null, null, Calendar.DAY_OF_MONTH
        );
        spnMulai.setModel(mulai);
        spnMulai.setEditor(new javax.swing.JSpinner.DateEditor(spnMulai, "yyyy-MM-dd"));

        SpinnerDateModel akhir = new SpinnerDateModel(
                new java.util.Date(), null, null, Calendar.DAY_OF_MONTH
        );
        spnAkhir.setModel(akhir);
        spnAkhir.setEditor(new javax.swing.JSpinner.DateEditor(spnAkhir, "yyyy-MM-dd"));
    }

    private void LoadData() {
    listTanggal.clear();
    listTotal.clear();

    try {
        Connection c = koneksi.Go();
        String sql = """
            SELECT tanggal, SUM(total) AS total_harian
            FROM penjualan
            WHERE tanggal BETWEEN ? AND ?
            GROUP BY tanggal
            ORDER BY tanggal
        """;

        PreparedStatement ps = c.prepareStatement(sql);
        java.util.Date d1 = (java.util.Date) spnMulai.getValue();
        java.util.Date d2 = (java.util.Date) spnAkhir.getValue();

        ps.setDate(1, new java.sql.Date(d1.getTime()));
        ps.setDate(2, new java.sql.Date(d2.getTime()));


        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            listTanggal.add(rs.getString("tanggal"));
            listTotal.add(rs.getDouble("total_harian"));
        }

        System.out.println("Jumlah data: " + listTotal.size());

        panelGrafik.repaint(); // 🔥 WAJIB

    } catch (Exception e) {
        e.printStackTrace();
    }
}

   private void drawGrafik(Graphics g) {
    if (listTotal.isEmpty()) return;

    Graphics2D g2 = (Graphics2D) g;
    int w = panelGrafik.getWidth();
    int h = panelGrafik.getHeight();

    int padding = 40;

    // Cari nilai maksimum
    double max = Collections.max(listTotal);

    // Gambar sumbu
    g2.drawLine(padding, h - padding, w - padding, h - padding); // X
    g2.drawLine(padding, padding, padding, h - padding);        // Y

    int n = listTotal.size();
    int stepX = (w - 2 * padding) / (n - 1);

    int prevX = padding;
    int prevY = h - padding;

    for (int i = 0; i < n; i++) {
        int x = padding + (i * stepX);
        int y = h - padding - (int) ((listTotal.get(i) / max) * (h - 2 * padding));

        g2.fillOval(x - 3, y - 3, 6, 6);

        if (i > 0) {
            g2.drawLine(prevX, prevY, x, y);
        }

        prevX = x;
        prevY = y;
    }
    System.out.println("paintComponent DIPANGGIL");

}


}
