/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import konektor.koneksi;

/**
 *
 * @author LENOVO
 */
public class KinerjaKasir extends javax.swing.JPanel {

    /**
     * Creates new form KinerjaKasir
     */
    public KinerjaKasir() {
        initComponents();
        initSpinnerTanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnMulai = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnAkhir = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN KINERJA KASIR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Masukkan Tanggal");

        spnMulai.setModel(new javax.swing.SpinnerDateModel());

        jLabel2.setText("S/D");

        spnAkhir.setModel(new javax.swing.SpinnerDateModel());

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kasir", "Transaksi", "Item", "Pendapatan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnMulai, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spnAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spnAkhir;
    private javax.swing.JSpinner spnMulai;
    // End of variables declaration//GEN-END:variables

    private void initSpinnerTanggal() {

    SpinnerDateModel modelMulai = new SpinnerDateModel(
        new java.util.Date(),
        null,
        null,
        Calendar.DAY_OF_MONTH
    );
    spnMulai.setModel(modelMulai);
    spnMulai.setEditor(new javax.swing.JSpinner.DateEditor(spnMulai, "dd-MM-yyyy"));

    SpinnerDateModel modelAkhir = new SpinnerDateModel(
        new java.util.Date(),
        null,
        null,
        Calendar.DAY_OF_MONTH
    );
    spnAkhir.setModel(modelAkhir);
    spnAkhir.setEditor(new javax.swing.JSpinner.DateEditor(spnAkhir, "dd-MM-yyyy"));
}

    private void LoadData () {

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear table

    java.util.Date tglMulai = (java.util.Date) spnMulai.getValue();
    java.util.Date tglAkhir = (java.util.Date) spnAkhir.getValue();

    String sql =
        "SELECT u.nama, " +
        "COUNT(DISTINCT p.id_penjualan) AS jumlah_transaksi, " +
        "COALESCE(SUM(dp.qty),0) AS total_item, " +
        "COALESCE(SUM(dp.qty * dp.harga),0) AS total_pendapatan " +
        "FROM pengguna u " +
        "JOIN penjualan p ON u.id_pengguna = p.id_pengguna " +
        "JOIN detail_penjualan dp ON p.id_penjualan = dp.id_penjualan " +
        "WHERE u.jabatan = 'kasir' " +
        "AND p.tanggal BETWEEN ? AND ?"+
        "GROUP BY u.id_pengguna, u.nama " +
        "ORDER BY total_pendapatan DESC";

    try {
        Connection conn = koneksi.Go();
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setDate(1, new Date(tglMulai.getTime()));
        ps.setDate(2, new Date(tglAkhir.getTime()));

        ResultSet rs = ps.executeQuery();

        int no = 1;
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("nama"),
                rs.getInt("jumlah_transaksi"),
                rs.getInt("total_item"),
                rs.getDouble("total_pendapatan")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    
}
