/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import dialogs.AddNewUser;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import dialogs.AddNewUser;
import konektor.koneksi;
import konektor.pegawai;
import dialogs.editUser;
import dialogs.HapusUser;

/**
 *
 * @author LENOVO
 */
public class Manageuser extends javax.swing.JPanel {
    pegawai Px;
    /**
     * Creates new form coba
     */
    public Manageuser() {
        initComponents();
        
        refreshData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        klmCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("TAMBAH");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("HAPUS");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 204, 51));
        btnRefresh.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        klmCari.setText("Cari user disini...");
        klmCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klmCariActionPerformed(evt);
            }
        });
        klmCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                klmCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(klmCari, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klmCari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnRefresh)
                    .addComponent(btnAdd))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Jabatan", "Username", "Email", "Password"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddNewUser NU = new AddNewUser(null, true);
        NU.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() != -1){
            editUser em = new editUser(null, true);
            em.P = Px;
            em.setVisible(true); 
        }else {
            
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        jTable1.clearSelection();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int n = jTable1.getSelectedRow();
        if (n != -1){
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            //extraksi data
            Px = new pegawai();
            String IDuser = jTable1.getValueAt(n, 0).toString();
            int ID = Integer.valueOf(IDuser);
            String Nama = jTable1.getValueAt(n, 1).toString();
            String Jabatan = jTable1.getValueAt(n, 2).toString();
            String Username = jTable1.getValueAt(n, 3).toString();
            String Email = jTable1.getValueAt(n, 4).toString();
            String Password = jTable1.getValueAt(n, 5).toString();
            Px.setId(ID);
            Px.setNama(Nama);
            Px.setJabatan(Jabatan);
            Px.setUsername(Username);
            Px.setEmail(Email);
            Px.setPassword(Password);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        HapusUser hu = new HapusUser(null, true);
        hu.p = Px;
        hu.setVisible(true);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void klmCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_klmCariKeyReleased
        // TODO add your handling code here:
        searchDataUser();
    }//GEN-LAST:event_klmCariKeyReleased

    private void klmCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klmCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klmCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField klmCari;
    // End of variables declaration//GEN-END:variables

    public static void refreshData(String string){
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int i = model.getRowCount()-1; i >=0; i--) {
                model.removeRow(i); 
            }

            Connection K = koneksi.Go();
            String Q = "SELECT * FROM pengguna";
            Statement S = K.createStatement();
            ResultSet R = S.executeQuery(Q);
            while (R.next()){                
                int id = R.getInt("id_pengguna");
                String nama = R.getString("nama");
                String jabatan = R.getString("jabatan");
                String username = R.getString("username");
                String email = R.getString("email");
                String password = R.getString("password");
                Object[] datausers = {id,nama,jabatan,username,email,password};
                model.addRow(datausers); 
            }
            
        } catch (Exception e) {
        }
    }


    private void searchDataUser() {
        String key = klmCari.getText().trim();

        if (key.isEmpty() || key.equalsIgnoreCase("Cari user disini...")) {
            refreshData("");
            return;
        }

        String where = " WHERE " +
            "id_pengguna LIKE '%" + key + "%' OR " +
            "nama LIKE '%" + key + "%' OR " +
            "jabatan LIKE '%" + key + "%' OR " +
            "username LIKE '%" + key + "%' OR " +
            "email LIKE '%" + key + "%'";

//        System.out.println("String WHERE yang dibuat: " + where);
        refreshData(where);
    }
}
