/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salinanminus;
import javax.swing.JFrame;
import konektor.pegawai;
import dialogs.profil;
import panel.cs;
import panel.Lpr;
import panel.RiwayarTransaksi;
/**
 *
 * @author bolem
 */
public class DashboardKasir extends javax.swing.JFrame {
    public pegawai P;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardKasir.class.getName());
    

    /**
     * Creates new form DashboardKasir
     */
    public DashboardKasir() {
        initComponents();
        this.P = P;
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        minus = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bgatas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        bgside = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.setLayout(null);

        minus.setBackground(new java.awt.Color(255, 255, 255));
        minus.setFont(new java.awt.Font("Tw Cen MT", 1, 70)); // NOI18N
        minus.setForeground(new java.awt.Color(153, 153, 255));
        minus.setText("Minus Electric");
        jPanel2.add(minus);
        minus.setBounds(190, 90, 440, 77);

        nama.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setText("nama");
        jPanel2.add(nama);
        nama.setBounds(1220, 70, 240, 30);

        btnLogout.setBackground(new java.awt.Color(255, 0, 51));
        btnLogout.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout);
        btnLogout.setBounds(1230, 190, 220, 40);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo 150.png"))); // NOI18N
        jPanel2.add(logo);
        logo.setBounds(10, 50, 150, 160);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton1.setText("Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(1230, 130, 220, 40);

        bgatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg atas.jpg"))); // NOI18N
        jPanel2.add(bgatas);
        bgatas.setBounds(0, 0, 1580, 240);

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1570, 240));

        jPanel3.setLayout(null);

        btnTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel3.add(btnTransaksi);
        btnTransaksi.setBounds(60, 10, 150, 50);

        btnLaporan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLaporan.setText("Laporan Harian");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jPanel3.add(btnLaporan);
        btnLaporan.setBounds(60, 150, 150, 50);

        btnRiwayat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRiwayat.setText("Riwayat Transaksi");
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });
        jPanel3.add(btnRiwayat);
        btnRiwayat.setBounds(60, 80, 150, 50);

        bgside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg pinggir.jpg"))); // NOI18N
        jPanel3.add(bgside);
        bgside.setBounds(0, 0, 280, 710);

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 298, 270, 540));

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 278, 1230, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1600bg.jpg"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 8, 1570, 980));

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        login P = new login();
        this.setVisible(false);
        P.setVisible(true);
        P.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        cs panelCS = new cs(P);   // kirim pegawai
        setPanel(panelCS);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
        RiwayarTransaksi rt = new RiwayarTransaksi();
        setPanel(rt);
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         nama.setText(P.getUsername());
    }//GEN-LAST:event_formWindowOpened

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        Lpr laporan = new Lpr ();
        setPanel(laporan);
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        profil pf = new profil(this, true);
        pf.setDataProfil(P);
        pf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardKasir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgatas;
    private javax.swing.JLabel bgside;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minus;
    private javax.swing.JLabel nama;
    // End of variables declaration//GEN-END:variables
    private void setPanel(javax.swing.JPanel panel) {
    jPanel4.removeAll();
    jPanel4.add(panel);
    jPanel4.repaint();
    jPanel4.revalidate();
}
}
