/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salinanminus;

import dialogs.profil;
import java.awt.Frame;
import konektor.pegawai;
import java.awt.BorderLayout;
import panel.ProdukTerlaris;
import panel.ProdukTerjual;
import panel.Pendapatan;
import panel.Grafik;
import panel.KinerjaKasir;
import panel.RiwayarTransaksi;


/**
 *
 * @author LENOVO
 */
public class DashboardManager extends javax.swing.JFrame {
    public pegawai P;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardManager.class.getName());

    /**
     * Creates new form DashboardManager
     */
    public DashboardManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        minus = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        bgatas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnTerlaris = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        btnKinerja = new javax.swing.JButton();
        btnGrafik = new javax.swing.JButton();
        btnPendapatan = new javax.swing.JButton();
        btnProdukTerjual = new javax.swing.JButton();
        bgside = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.setLayout(null);

        minus.setBackground(new java.awt.Color(255, 255, 255));
        minus.setFont(new java.awt.Font("Tw Cen MT", 1, 70)); // NOI18N
        minus.setForeground(new java.awt.Color(153, 153, 255));
        minus.setText("Minus Electric");
        jPanel2.add(minus);
        minus.setBounds(190, 90, 440, 77);

        nama.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setText("nama");
        jPanel2.add(nama);
        nama.setBounds(1220, 70, 240, 30);

        btnLogout.setBackground(new java.awt.Color(255, 0, 51));
        btnLogout.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout);
        btnLogout.setBounds(1230, 180, 220, 40);

        btnProfile.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        jPanel2.add(btnProfile);
        btnProfile.setBounds(1230, 130, 220, 40);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo 150.png"))); // NOI18N
        jPanel2.add(logo);
        logo.setBounds(10, 50, 150, 160);

        bgatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg atas.jpg"))); // NOI18N
        jPanel2.add(bgatas);
        bgatas.setBounds(-3, -4, 1580, 240);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 1570, 240));

        jPanel3.setLayout(null);

        btnTerlaris.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTerlaris.setText("Produk Terlaris");
        btnTerlaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerlarisActionPerformed(evt);
            }
        });
        jPanel3.add(btnTerlaris);
        btnTerlaris.setBounds(60, 0, 150, 50);

        btnRiwayat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRiwayat.setText("Riwayat Penjualan");
        btnRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatActionPerformed(evt);
            }
        });
        jPanel3.add(btnRiwayat);
        btnRiwayat.setBounds(60, 400, 150, 50);

        btnKinerja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKinerja.setText("Kinerja Kasir");
        btnKinerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKinerjaActionPerformed(evt);
            }
        });
        jPanel3.add(btnKinerja);
        btnKinerja.setBounds(60, 320, 150, 50);

        btnGrafik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGrafik.setText("Grafik Penjualan");
        btnGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafikActionPerformed(evt);
            }
        });
        jPanel3.add(btnGrafik);
        btnGrafik.setBounds(60, 240, 150, 50);

        btnPendapatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPendapatan.setText("Pendapatan");
        btnPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatanActionPerformed(evt);
            }
        });
        jPanel3.add(btnPendapatan);
        btnPendapatan.setBounds(60, 160, 150, 50);

        btnProdukTerjual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProdukTerjual.setText("Produk Terjual");
        btnProdukTerjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukTerjualActionPerformed(evt);
            }
        });
        jPanel3.add(btnProdukTerjual);
        btnProdukTerjual.setBounds(60, 80, 150, 50);

        bgside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg pinggir.jpg"))); // NOI18N
        jPanel3.add(bgside);
        bgside.setBounds(0, 0, 280, 710);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 540));

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 1230, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1600bg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 980));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        login P = new login();
        this.setVisible(false);
        P.setVisible(true);
        P.setExtendedState(Frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        profil pf = new profil(this, true);
        pf.setDataProfil(P);
        pf.setVisible(true);

    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnTerlarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerlarisActionPerformed
        // TODO add your handling code here:
        tampilPanel(new ProdukTerlaris());
    }//GEN-LAST:event_btnTerlarisActionPerformed

    private void btnProdukTerjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukTerjualActionPerformed
        // TODO add your handling code here:
        tampilPanel(new ProdukTerjual());
    }//GEN-LAST:event_btnProdukTerjualActionPerformed

    private void btnPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatanActionPerformed
        // TODO add your handling code here:
         tampilPanel(new Pendapatan());
    }//GEN-LAST:event_btnPendapatanActionPerformed

    private void btnGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafikActionPerformed
        // TODO add your handling code here:
        tampilPanel(new Grafik());
    }//GEN-LAST:event_btnGrafikActionPerformed

    private void btnKinerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKinerjaActionPerformed
        // TODO add your handling code here:
        tampilPanel(new KinerjaKasir());
    }//GEN-LAST:event_btnKinerjaActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
         tampilPanel(new RiwayarTransaksi());
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nama.setText(P.getUsername());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardManager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgatas;
    private javax.swing.JLabel bgside;
    private javax.swing.JButton btnGrafik;
    private javax.swing.JButton btnKinerja;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPendapatan;
    private javax.swing.JButton btnProdukTerjual;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnTerlaris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel minus;
    private javax.swing.JLabel nama;
    // End of variables declaration//GEN-END:variables

    private void tampilPanel(javax.swing.JPanel panel) {
    jPanel4.removeAll();
    jPanel4.setLayout(new BorderLayout());
    jPanel4.add(panel, BorderLayout.CENTER);
    jPanel4.revalidate();
    jPanel4.repaint();
}

    
}
